# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sample Jekyll Page
email: Jessie.L.Anderson.18@dartmouth.edu
description: > # this means to ignore newlines until "baseurl:"
  N/A
baseurl: "/jessies-jekyll/" # the subpath of your site, e.g. /blog
url: "http://jessie-anderson/github.io/cs52-workshop-2" # the base hostname & protocol for your site
twitter_username: N/A
github_username:  jessie-anderson

# Build settings
markdown: kramdown
include: [`_pages`]
